# coding: utf8
import demo_data_service
import order_paid_handle_service
import send_order_email_task
import send_order_template_message_task
import notify_kuaidi_task
import delivery_item_shipped_handle_service



