# -*- coding: utf-8 -*-

import notify_kuaidi_task
import send_delivery_item_phone_message_task
import send_order_email_task
import send_order_template_message_task


from order_action_handle_service import delivery_item_applied_for_redfunding_handle_service
from order_action_handle_service import delivery_item_cancelled_handel_service
from order_action_handle_service import delivery_item_finished_handle_service
from order_action_handle_service import delivery_item_paid_handle_service
from order_action_handle_service import delivery_item_refunded_handle_service
from order_action_handle_service import delivery_item_ship_info_updated_handle_service
from order_action_handle_service import delivery_item_shipped_handle_service
from order_action_handle_service import order_applied_for_refunding_handle_service
from order_action_handle_service import order_cancelled_handle_service
from order_action_handle_service import order_finished_handle_service
from order_action_handle_service import order_paid_handle_service
from order_action_handle_service import order_refunded_handle_service
from order_action_handle_service import order_shipped_handle_service


import test_send_handle